### ISSUE TITLE
AlpsItem の profileUrl と asdUrl は goProfile と goAsd が適切ではないか

### ISSUE THREAD

**Issue by NaokiTsuchiya** [ma-alps/spec#36]
アプリケーション状態としての [`AlpsItem`](https://ma-alps.github.io/spec/docs/semantic.AlpsItem.html) を考えると、`profileUrl` や `asdUrl` ではなく、 `goProfile` や `goAsd` のような遷移として定義するのが良さそう？

置き換えはともかく、遷移自体はあっても良さそう。

ジャッジしたいこと

- `profileUrl` を `goProfile` に、`asdUrl` を `goAsd` に変更
- `profileUrl` と `asdUrl` はそのままに、 `goProfile` と `goAsd` を追加
- そのままなにもしない

**Comment by NaokiTsuchiya** [comment]
アプリケーション状態としてはurlではなく、URLの先の表現に関心があるように思われる

**Comment by NaokiTsuchiya** [comment]
asdUrl や profileUrl ではなく、 ASDやProfileの表現が embedde されているイメージ

**Comment by koriym** [comment]
> profileUrl や asdUrl ではなく、 goProfile や goAsd のような遷移として定義するのが良さそう？

これはいい視点ですね。
その状態に遷移したいかどうかだと思うのですが、この場合「遷移したい」ですね。

statusの時にもディスカッションしたようにYAGNIで行きましょうか。

> profileUrl を goProfile に、asdUrl を goAsd に変更

これに変更でどうですか？
問題があるならまた考えるということで。

**Comment by NaokiTsuchiya** [comment]
`doCreate` や `doEdit` のような遷移には `profileUrl` や `asdUrl` は必要？

**Comment by NaokiTsuchiya** [comment]
以下のような感じをイメージしていたけど、今だと一つのdescriptorで同じidを含められない気がする（試す）

```xml
<descriptor id="url" />

<descriptor id="doCreate">
  <descriptor href="url" title="profileUrl" >
  <descriptor href="url" title="asdUrl" >
</descriptor>
```
